task_manager/labels/urls.py
from django.urls import path
from . import views

app_name = "labels"

urlpatterns = [
    path("", views.LabelsListView.as_view(), name="labels_list"),
    path("create/", views.LabelCreateView.as_view(), name="labels_create"),
    path('<int:pk>/', views.LabelDetailView.as_view(), name='labels_detail'),
    path(
        "<int:pk>/update/",
        views.LabelUpdateView.as_view(),
        name="labels_update"
    ),
    path(
        "<int:pk>/delete/",
        views.LabelDeleteView.as_view(),
        name="labels_delete"
    ),
]

task_manager/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path(
        "",
        views.TaskListView.as_view(),
        name="tasks_list"
    ),
    path(
        "create/",
        views.TaskCreateView.as_view(),
        name="tasks_create"
    ),
    path(
        '<int:pk>/',
        views.TaskDetailView.as_view(),
        name='tasks_detail'
    ),
    path(
        "<int:pk>/update/",
        views.TaskUpdateView.as_view(),
        name="tasks_update"
    ),
    path(
        "<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="tasks_delete"
    ),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomePageView, CustomLoginView, CustomLogoutView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path(
        "login/",
        CustomLoginView.as_view(
            template_name="registration/login.html"
        ),
        name="login"
    ),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("labels/", include("task_manager.labels.urls")),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

task_manager/users/urls.py
from django.urls import path

from .views import (
    UsersListView,
    UsersCreateView,
    UsersUpdateView,
    UsersDeleteView
)

app_name = "users"

urlpatterns = [
    path(
        "",
        UsersListView.as_view(),
        name="users_list"
    ),
    path(
        "create/",
        UsersCreateView.as_view(),
        name="users_create"
    ),
    path(
        "<int:pk>/update/",
        UsersUpdateView.as_view(),
        name="users_update"
    ),
    path(
        "<int:pk>/delete/",
        UsersDeleteView.as_view(),
        name="users_delete"
    ),
]

task_manager/statuses/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ["name"]

task_manager/labels/views.py
import logging
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.views import FilterView

from .models import Label
from task_manager.tasks.models import Task


logger = logging.getLogger("labels")


class FormLoggerMixin:
    """
    Логирует успешное сохранение формы в классовых представлениях.
    Используется вместе с CreateView/UpdateView/DeleteView.
    """

    log_message: str = "Object saved: {obj}"

    def form_valid(self, form):
        response = super().form_valid(form)
        logger.info(self.log_message.format(obj=self.object))
        return response


# ---------------------------
# Список меток
# ---------------------------
class LabelsListView(LoginRequiredMixin, FilterView, ListView):
    model = Label
    template_name = 'labels/list.html'
    context_object_name = "labels"


# ---------------------------
# Вывод конкретной метки
# ---------------------------
class LabelDetailView(LoginRequiredMixin, DetailView):
    model = Label
    template_name = 'labels/detail.html'
    context_object_name = "labels"


# ---------------------------
# Создание метки
# ---------------------------
class LabelCreateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    CreateView
):
    model = Label
    template_name = 'labels/create.html'
    context_object_name = "label"
    fields = ['name']
    success_url = reverse_lazy("labels:labels_list")
    success_message = _("Метка успешно создана")
    log_message = "Создана метка: {obj}"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# ---------------------------
# Редактирование метки
# ---------------------------
class LabelUpdateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Label
    template_name = 'labels/update.html'
    context_object_name = "label"
    fields = ['name']
    success_url = reverse_lazy("labels:labels_list")
    success_message = _("Метка успешно изменена")
    log_message = "Изменена метка: {obj}"


# ---------------------------
# Удаление метки
# ---------------------------
class LabelDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = "labels/delete.html"
    context_object_name = "label"
    success_url = reverse_lazy("labels:labels_list")

    def post(self, request, *args, **kwargs):
        """
        Переопределяем POST, 
        чтобы перед удалением проверить связанные задачи.
        """
        self.object = self.get_object()
        label_id = self.object.id

        # Проверяем, есть ли задачи с этой меткой
        if Task.objects.filter(labels=self.object).exists():
            messages.error(
                request,
                "Невозможно удалить метку,"
                "потому что она используется в задачах"
            )
            logger.warning(
                f"Попытка удалить метку {label_id}, связанную с задачами"
            )
            return redirect(self.success_url)

        # Если связей нет — вызываем стандартное удаление
        response = super().post(request, *args, **kwargs)
        messages.success(request, "Метка успешно удалена")
        logger.info(f"Метка {label_id} удалена")
        return response

task_manager/statuses/views.py
import logging
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Status
from task_manager.tasks.models import Task
from .forms import StatusForm

logger = logging.getLogger("statuses")


class FormLoggerMixin:
    """
    Логирует успешное сохранение/изменение объекта
    в CreateView/UpdateView/DeleteView.
    """

    log_message = "Создан объект: {obj}"

    def form_valid(self, form):
        response = super().form_valid(form)
        logger.info(self.log_message.format(obj=self.object))
        return response


# ---------------------------
# Список статусов
# ---------------------------
class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = "statuses/list.html"
    context_object_name = "statuses"


# ---------------------------
# Создание статуса
# ---------------------------
class StatusCreateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    CreateView
):
    model = Status
    form_class = StatusForm
    template_name = "statuses/create.html"
    success_url = reverse_lazy("statuses:statuses_list")
    success_message = _("Статус успешно создан")
    log_message = "Создан статус: {obj}"


# ---------------------------
# Обновление статуса
# ---------------------------
class StatusUpdateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Status
    form_class = StatusForm
    template_name = "statuses/update.html"
    success_url = reverse_lazy("statuses:statuses_list")
    success_message = _("Статус успешно изменен")
    log_message = "Статус обновлён: {obj}"


# ---------------------------
# Удаление статуса
# ---------------------------
class StatusDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Status
    template_name = "statuses/delete.html"
    success_url = reverse_lazy("statuses:statuses_list")
    success_message = _("Статус успешно удален")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        status_id = self.object.id

        if Task.objects.filter(status=self.object).exists():
            messages.error(
                request,
                _("Невозможно удалить статус, потому что он используется")
            )
            logger.warning(
                f"Попытка удалить статус {status_id}, который используется"
            )
            return redirect("statuses:statuses_list")

        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        logger.info(f"Статус {status_id} удален")
        return response

task_manager/tasks/views.py
import logging
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django_filters.views import FilterView

from .filters import TaskFilter
from .models import Task
from .forms import TaskForm


logger = logging.getLogger("tasks")


class FormLoggerMixin:
    """
    Логирует успешное сохранение формы в классовых представлениях.
    Используется вместе с CreateView/UpdateView/DeleteView.
    """

    log_message: str = "Object saved: {obj}"

    def form_valid(self, form):
        response = super().form_valid(form)
        logger.info(self.log_message.format(obj=self.object))
        return response


# ---------------------------
# Список задач
# ---------------------------
class TaskListView(LoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter


# ---------------------------
# Вывод конкретной задачи
# ---------------------------
class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = "task"


# ---------------------------
# Создание задачи
# ---------------------------
class TaskCreateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    CreateView
):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    context_object_name = "task"
    success_url = reverse_lazy("tasks:tasks_list")
    success_message = _("Задача успешно создана")
    log_message = "Создана задача: {obj}"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# ---------------------------
# Редактирование задачи
# ---------------------------
class TaskUpdateView(
    LoginRequiredMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Task
    context_object_name = "task"
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy("tasks:tasks_list")
    success_message = _("Задача успешно изменена")
    log_message = "Изменена задача: {obj}"


# ---------------------------
# Удаление задачи
# ---------------------------
class TaskDeleteView(
    UserPassesTestMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    DeleteView
):
    model = Task
    template_name = "tasks/delete.html"
    context_object_name = "task"
    success_url = reverse_lazy("tasks:tasks_list")
    success_message = _("Задача успешно удалена")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def handle_no_permission(self):
        messages.error(
            self.request,
            _("Задачу может удалить только ее автор")
        )
        return redirect('tasks:tasks_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        logger.info(f"Задача удалена: {self.object}")
        messages.success(request, _("Задача успешно удалена"))
        return super().delete(request, *args, **kwargs)

task_manager/users/views.py
import logging
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from .forms import RegisterForm, CustomUserChangeForm
from task_manager.tasks.models import Task

logger = logging.getLogger("users")


class FormLoggerMixin:
    """
    Логирует успешное сохранение формы в классовых представлениях.
    Используется вместе с CreateView/UpdateView/DeleteView.
    """

    log_message: str = "Object saved: {obj}"

    def form_valid(self, form):
        response = super().form_valid(form)
        logger.info(self.log_message.format(obj=self.object))
        return response


class PermissionMessageMixin:

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                _("Вы не авторизованы! Пожалуйста, выполните вход.")
            )
            return redirect("login")
        messages.error(
            self.request,
            _("У вас нет прав для изменения другого пользователя.")
        )
        return redirect("users:users_list")


class UserPermissionTestMixin(UserPassesTestMixin):
    """
    Проверяет, что пользователь изменяет или удаляет только свой профиль,
    либо является суперпользователем.
    """

    def test_func(self):
        user = self.get_object()
        return self.request.user.pk == user.pk or self.request.user.is_superuser


class UsersListView(ListView):
    model = User
    template_name = "users/list.html"
    context_object_name = "users"


class UsersCreateView(FormLoggerMixin, SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = "users/create.html"
    success_url = "/login/"
    success_message = _("Пользователь успешно зарегистрирован")
    log_message = "Создать пользователя: {obj.username}"


class UsersUpdateView(
    PermissionMessageMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    LoginRequiredMixin,
    UserPermissionTestMixin,
    UpdateView,
):
    model = User
    form_class = CustomUserChangeForm
    template_name = "users/update.html"
    success_url = reverse_lazy("users:users_list")
    success_message = _("Пользователь успешно изменен")
    log_message = "Пользователь обновлен: {obj.username}"


class UsersDeleteView(
    PermissionMessageMixin,
    FormLoggerMixin,
    SuccessMessageMixin,
    LoginRequiredMixin,
    UserPermissionTestMixin,
    DeleteView
):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users:users_list")

    def post(self, request, *args, **kwargs):
        """
        Переопределяем POST, чтобы перед удалением проверить связанные задачи.
        """
        self.object = self.get_object()  # объект берется по pk из URL
        user_id = self.object.id

        # Проверяем, есть ли задачи, автором которых является пользователь
        if Task.objects.filter(author=self.object).exists():
            messages.error(
                request,
                _("Невозможно удалить пользователя, потому что он используется")
            )
            logger.warning(
                f"Попытка удалить пользователя {user_id},"
                f"который является автором задач"
            )
            return redirect("users:users_list")

        # Если связей нет — вызываем стандартное удаление
        response = super().delete(request, *args, **kwargs)
        messages.success(request, _("Пользователь успешно удален"))
        logger.info(f"Пользователь {user_id} удалён")
        return response

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'index.html'

    GREETING = _('Првиетсвуем в Хекслет!')
    HEADING = _('Практические курсы программирования')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['greeting'] = self.GREETING
        context['heading'] = self.HEADING
        return context


class CustomLogoutView(LogoutView):
    next_page = '/'
    LOGGRD_OUT = _('Вы разлогинены')

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, self.LOGGRD_OUT)
        return super().dispatch(request, *args, **kwargs)


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = 'registration/login.html'
    success_message = _('Вы залогинены')

task_manager/templates/tasks/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<form action="{% url 'tasks:tasks_create' %}" method="post">
    <div class="row justify-content-center">
        <div class="col-sm-8">
            <h1 class="my-4">{% trans 'Создать задачу' %}</h1>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn btn-primary" type="submit" value="{% trans 'Создать' context 'verb' %}">
        </div>
    </div>
</form>
  
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<div class="container my-4">
    <h1 class="my-4">{% trans "Подтвердить удаление" %}</h1>
    <p>{% trans "Вы уверены, что хотите удалить задачу" %}<strong>{{ user.get_full_name }}</strong>?</p>
    
    <form action="{% url 'tasks:tasks_delete' task.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans "Да, удалить" %}</button>
    </form>
</div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">Просмотр задачи</h1>
    <div class="card">
        <div class="card-header" style="background-color: #e6e6fa;">
            <h2 class="my-2">{{ task.name }}</h2>
        </div>
        <div class="card-body bg-light">
            <p>{{ task.description }}</p>
            <hr>
            <div class="container">
                <div class="row p-1">
                    <div class="col font-weight-bold">{% trans "Автор" %}</div>
                    <div class="col">{{ task.author.get_full_name }}</div>
                </div>
                <div class="row p-1">
                    <div class="col font-weight-bold">{% trans "Исполнитель" %}</div>
                    <div class="col">{{ task.executor.get_full_name }}</div>
                </div>
                <div class="row p-1">
                    <div class="col font-weight-bold">{% trans "Статус" %}</div>
                    <div class="col">{{ task.status }}</div>
                </div>
                <div class="row p-1">
                    <div class="col font-weight-bold">{% trans "Дата создания" %}</div>
                    <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
                </div>
                <div class="row p-1">
                    <div class="col">
                        <h6>{% trans "Метки" %}:</h6>
                        <ul class="pl-3">
                            {% for label in task.labels.all %}
                            <li>{{ label }}</li>
                            {% empty %}
                            <li>(нет меток)</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="row justify-content-end">
                    <a href="{% url 'tasks:tasks_update' task.id %}">Изменить</a>
                    <a href="{% url 'tasks:tasks_delete' task.id %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<div class="container-fluid my-4">
    <div class="row justify-content-center">

        <!-- Левая сторона: Карточка с фильтрацией -->
        <div class="col-md-3 col-xl-2" style="margin-top: 170px;">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{% trans "Фильтры" %}</h5>
                </div>

                <form method="get" class="my-4 mb-3 mx-2">
                    {% bootstrap_form filter.form layout='vertical' show_label=True %}
                    <button type="submit" class="btn btn-primary mb-3 mx-2">{% trans "Показать" %}</button>
                </form>
            </div>
        </div>
        
        <!-- Правая сторона: Форма со списком -->
        <div class="col-md-9 col-xl-9">
            <h1 class="my-1">{% trans "Задачи" %}</h1>
            <a class="btn btn-primary mb-3" href="{% url 'tasks:tasks_create'%}">{% trans "Создать задачу" %}</a>
            
            <form class="my-4">
                <table class="table table-striped table-hover align-middle">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>{% trans "Имя" %}</th>
                            <th>{% trans "Статус" %}</th>
                            <th>{% trans "Автор" %}</th>
                            <th>{% trans "Исполнитель" %}</th>
                            <th>{% trans "Дата создания" %}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for task in tasks %}
                        <tr>
                            <td>{{ task.id }}</td>
                            <td><a href="{% url 'tasks:tasks_detail' task.id %}">{{ task.name }}</a></td>
                            <td>{{ task.status }}</td>
                            <td>{{ task.author.get_full_name }}</td>
                            <td>{{ task.executor.get_full_name }}</td>
                            <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
                            <td>
                                <a href="{% url 'tasks:tasks_update' task.id %}">{% trans "Изменить" %}</a>
                                <br>
                                <a href="{% url 'tasks:tasks_delete' task.id %}">{% trans "Удалить" %}</a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="8" class="text-center text-muted">
                            {% trans "Нет задачь" %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<form action="{% url 'tasks:tasks_update' task.id %}" method="post">
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <h1 class="my-4">{% trans "Изменить задачу" %}</h1>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn btn-primary" type="submit" value="{% trans 'Изменить' context 'verb' %}">
        </div>
    </div>
</form>
{% endblock %}